# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs

name: ci
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [16.x, 18.x, 20.x, lts/*, latest]
    runs-on: ${{ matrix.os }}
    steps:
      - if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2 libxml2-dev
      - uses: actions/checkout@v4
      - run: touch package-lock.json  # TODO: Remove this line.
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm update  # TODO: Remove this line.
      # - run: npm ci
      # - run: npm install
      - run: npm install --build-from-source
      - run: npm run build --if-present
      - run: npm test
